# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.

include: package:flutter_lints/flutter.yaml

analyzer: 
  exclude: 
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    unnecessary_await_in_return: true
    prefer_single_quotes: true
    prefer_final_locals: true
    avoid_unused_constructor_parameters: true
    always_declare_return_types: true